import { parseM3U } from './core/channel-catalog.js?v=20260920-1021';

const BUILD_ID = '20260920-1635';
const DB_NAME = 'webtv-v2-playlists';
const STORE = 'playlists';
const ACTIVE_KEY = 'webtv_v2_active_playlist';
const DEFAULT_WORKER = 'https://source-huntatonisworkersdev.atonis.workers.dev';
const $ = id => document.getElementById(id);

let dbPromise;
let tested = null;

function log(message){const box=$('diagnostic-log');if(!box)return;const stamp=new Date().toLocaleTimeString();box.textContent=`[${stamp}] ${message}\n${box.textContent}`.slice(0,18000);}
function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return dbPromise;}
async function allSaved(){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)));req.onerror=()=>reject(req.error);});}
async function getSaved(id){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});}
async function putSaved(item){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(item);tx.oncomplete=()=>resolve(item);tx.onerror=()=>reject(tx.error);});}
async function removeSaved(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
function uid(){return `pl_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;}
function activeState(){try{return JSON.parse(localStorage.getItem(ACTIVE_KEY)||'null');}catch{return null;}}
function setActiveState(value){if(value)localStorage.setItem(ACTIVE_KEY,JSON.stringify(value));else localStorage.removeItem(ACTIVE_KEY);}
function setStatus(text,tone='idle'){const el=$('playlist-manager-status');if(!el)return;el.textContent=text;el.dataset.tone=tone;}
function selectedMode(){return document.querySelector('input[name="playlist-mode"]:checked')?.value||'replace';}
function summarize(text){const channels=parseM3U(text);const groups=[...new Set(channels.map(c=>c.group||'Other'))];return{channels,count:channels.length,groups:groups.length,sample:channels.slice(0,8).map(c=>c.name)};}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function renderPreview(summary,label='M3U preview'){const box=$('playlist-preview');if(!box)return;box.innerHTML='';const top=document.createElement('div');top.className='playlist-preview-top';top.innerHTML=`<strong>${escapeHtml(label)}</strong><span>${summary.count} channels · ${summary.groups} groups</span>`;box.appendChild(top);const chips=document.createElement('div');chips.className='playlist-preview-chips';for(const name of summary.sample){const chip=document.createElement('span');chip.textContent=name;chips.appendChild(chip);}if(summary.count>summary.sample.length){const more=document.createElement('span');more.textContent=`+${summary.count-summary.sample.length} more`;chips.appendChild(more);}box.appendChild(chips);}
async function fetchWithTimeout(url,timeout=9000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,{cache:'no-store',signal:c.signal});}finally{clearTimeout(t);}}
async function fetchPlaylist(url){const clean=String(url||'').trim();if(!/^https?:\/\//i.test(clean))throw new Error('Valid http/https playlist URL required');try{const r=await fetchWithTimeout(clean,9000);if(r.ok){const text=await r.text();if(summarize(text).count)return{text,via:'direct'};}}catch{}const proxy=`${DEFAULT_WORKER}/playlist-proxy?url=${encodeURIComponent(clean)}`;const r=await fetchWithTimeout(proxy,12000);if(!r.ok){let detail='';try{detail=(await r.json())?.error||'';}catch{}throw new Error(`Playlist fetch failed${detail?` · ${detail}`:` · HTTP ${r.status}`}`);}const text=await r.text();if(!summarize(text).count)throw new Error('No #EXTINF channels found');return{text,via:'worker'};}
function api(){return window.WebTVPlaylistAPI||null;}
async function applyText(text,mode,label){const bridge=api();if(!bridge)throw new Error('WebTV playlist bridge is not ready');const result=bridge.applyText(text,{mode,label});setStatus(`${label} loaded · ${result.imported} channels · ${mode}`,'ok');log(`PLAYLIST ${mode.toUpperCase()} · ${label} · ${result.imported} imported · ${result.total} total`);return result;}
async function testUrl(){const url=$('playlist-add-url')?.value.trim();if(!url)return;setStatus('Fetching playlist URL…','busy');try{const fetched=await fetchPlaylist(url);const summary=summarize(fetched.text);tested={text:fetched.text,url,type:'url',summary};renderPreview(summary,`URL test · ${fetched.via}`);setStatus(`Valid M3U · ${summary.count} channels`,'ok');}catch(error){setStatus(error.message,'error');log(`PLAYLIST URL TEST FAILED · ${error.message}`);}}
function testPaste(){const text=$('playlist-paste')?.value||'';const summary=summarize(text);if(!summary.count){setStatus('No #EXTINF channels found in pasted text','error');return;}tested={text,type:'paste',summary};renderPreview(summary,'Pasted M3U test');setStatus(`Valid M3U · ${summary.count} channels`,'ok');}
async function currentPayload(kind){if(kind==='url'){const url=$('playlist-add-url')?.value.trim();if(!url)throw new Error('Playlist URL is empty');if(tested?.type==='url'&&tested.url===url)return tested;const fetched=await fetchPlaylist(url);return{text:fetched.text,url,type:'url',summary:summarize(fetched.text)};}const text=$('playlist-paste')?.value||'';const summary=summarize(text);if(!summary.count)throw new Error('No channels found in pasted M3U');return{text,type:'paste',summary};}
async function loadTemporary(kind){try{setStatus('Preparing temporary playlist…','busy');const p=await currentPayload(kind);const label=kind==='url'?(p.url||'External URL'):'Pasted M3U';await applyText(p.text,selectedMode(),label);renderPreview(p.summary,'Loaded temporarily');}catch(error){setStatus(error.message,'error');}}
async function saveCurrent(kind){try{setStatus('Saving playlist…','busy');const p=await currentPayload(kind);const nameInput=kind==='url'?$('playlist-url-name'):$('playlist-paste-name');const fallback=kind==='url'?new URL(p.url).hostname:`Playlist ${new Date().toLocaleDateString('de-DE')}`;const name=(nameInput?.value||'').trim()||fallback;const now=Date.now();const item={id:uid(),name,type:kind,url:p.url||'',text:p.text,channelCount:p.summary.count,groupCount:p.summary.groups,createdAt:now,updatedAt:now};await putSaved(item);if(nameInput)nameInput.value='';setStatus(`${name} saved · ${p.summary.count} channels`,'ok');log(`PLAYLIST SAVED · ${name} · ${p.summary.count} channels`);await renderSaved();}catch(error){setStatus(error.message,'error');}}
function downloadM3U(item){const blob=new Blob([item.text],{type:'audio/x-mpegurl;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${item.name.replace(/[^a-z0-9α-ω_-]+/gi,'_')||'playlist'}.m3u`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function makeActive(item,mode){setActiveState({id:item.id,mode});await applyText(item.text,mode,item.name);await renderSaved();setStatus(`${item.name} is now active · ${mode}`,'ok');}
async function useRepo(){setActiveState(null);const bridge=api();if(!bridge)return;const result=bridge.resetToRepo();setStatus(`Repo Playlist active · ${result.total} channels`,'ok');log(`PLAYLIST ACTIVE · Repo Playlist · ${result.total} channels`);await renderSaved();}
function tinyButton(label,cls='ghost'){const b=document.createElement('button');b.type='button';b.className=`button ${cls} mini`;b.textContent=label;return b;}
async function renderSaved(){const box=$('saved-playlists'),count=$('saved-playlist-count');if(!box)return;const rows=await allSaved(),active=activeState();if(count)count.textContent=`${rows.length} saved`;box.innerHTML='';const repo=document.createElement('article');repo.className=`playlist-card builtin${!active?' active':''}`;repo.innerHTML=`<div class="playlist-card-icon">⌂</div><div class="playlist-card-main"><div class="playlist-card-title"><strong>Repo Playlist</strong>${!active?'<span class="playlist-active-badge">ACTIVE</span>':''}</div><span>Built-in fallback · GitHub repository</span></div>`;const repoActions=document.createElement('div');repoActions.className='playlist-card-actions';const repoLoad=tinyButton('Use','ghost');repoLoad.addEventListener('click',useRepo);repoActions.append(repoLoad);repo.append(repoActions);box.appendChild(repo);for(const item of rows){const isActive=active?.id===item.id;const card=document.createElement('article');card.className=`playlist-card${isActive?' active':''}`;const icon=document.createElement('div');icon.className='playlist-card-icon';icon.textContent=item.type==='url'?'↗':'≡';const main=document.createElement('div');main.className='playlist-card-main';const title=document.createElement('div');title.className='playlist-card-title';const strong=document.createElement('strong');strong.textContent=item.name;title.appendChild(strong);if(isActive){const badge=document.createElement('span');badge.className='playlist-active-badge';badge.textContent=`ACTIVE · ${active.mode}`;title.appendChild(badge);}const meta=document.createElement('span');meta.textContent=`${item.channelCount||0} channels · ${item.groupCount||0} groups${item.url?` · ${new URL(item.url).hostname}`:''}`;main.append(title,meta);const actions=document.createElement('div');actions.className='playlist-card-actions';const load=tinyButton('Load');load.addEventListener('click',()=>applyText(item.text,selectedMode(),item.name).catch(e=>setStatus(e.message,'error')));const activeBtn=tinyButton('Set Active','ghost');activeBtn.addEventListener('click',()=>makeActive(item,selectedMode()));const rename=tinyButton('Rename','ghost');rename.addEventListener('click',async()=>{const name=prompt('Playlist name',item.name);if(!name?.trim())return;await putSaved({...item,name:name.trim(),updatedAt:Date.now()});await renderSaved();});const exportBtn=tinyButton('Export','ghost');exportBtn.addEventListener('click',()=>downloadM3U(item));const del=tinyButton('Delete','danger');del.addEventListener('click',async()=>{if(!confirm(`Delete “${item.name}”?`))return;await removeSaved(item.id);if(active?.id===item.id){setActiveState(null);api()?.resetToRepo();}await renderSaved();setStatus(`${item.name} deleted`,'idle');});actions.append(load,activeBtn,rename,exportBtn,del);card.append(icon,main,actions);box.appendChild(card);}}
async function restoreActive(){const active=activeState();if(!active)return;const item=await getSaved(active.id);if(!item){setActiveState(null);return;}try{await applyText(item.text,active.mode||'replace',`${item.name} · startup`);}catch(error){setStatus(`Active playlist failed · ${error.message}`,'error');}}
function bind(){$('playlist-manager-toggle')?.addEventListener('click',()=>{const p=$('playlist-manager');if(p)p.hidden=!p.hidden;});$('playlist-manager-close')?.addEventListener('click',()=>{const p=$('playlist-manager');if(p)p.hidden=true;});$('playlist-test-url')?.addEventListener('click',testUrl);$('playlist-load-url')?.addEventListener('click',()=>loadTemporary('url'));$('playlist-save-url')?.addEventListener('click',()=>saveCurrent('url'));$('playlist-test-paste')?.addEventListener('click',testPaste);$('playlist-load-paste')?.addEventListener('click',()=>loadTemporary('paste'));$('playlist-save-paste')?.addEventListener('click',()=>saveCurrent('paste'));$('playlist-use-repo')?.addEventListener('click',useRepo);$('playlist-add-url')?.addEventListener('keydown',e=>{if(e.key==='Enter')testUrl();});}
bind();renderSaved().catch(error=>setStatus(`Playlist DB error · ${error.message}`,'error'));window.addEventListener('webtv:ready',()=>restoreActive().then(renderSaved).catch(error=>setStatus(error.message,'error')),{once:true});if(window.WebTVPlaylistAPI?.ready)restoreActive().then(renderSaved).catch(()=>{});log(`Playlist Manager loaded · build ${BUILD_ID}`);
