name: Update proxy-map.json

on:
  schedule:
    - cron: '*/15 * * * *'  # Κάθε 15 λεπτά
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download temp proxy data from Glitch
        run: |
          curl -s https://yellow-hulking-guan.glitch.me/streamPerfMap.temp.json -o temp.json

      - name: Merge into proxy-map.json
        run: |
          mkdir -p .data
          if [ -f proxy-map.json ]; then
            cp proxy-map.json .data/proxy-map.json
          else
            echo "{}" > .data/proxy-map.json
          fi

          node <<EOF
          const fs = require('fs');
          const oldData = JSON.parse(fs.readFileSync('.data/proxy-map.json', 'utf8'));
          const newData = JSON.parse(fs.readFileSync('temp.json', 'utf8'));
          let updated = false;

          for (const url in newData) {
            if (!oldData[url]) {
              oldData[url] = newData[url];
              updated = true;
            }
          }

          if (updated) {
            fs.writeFileSync('proxy-map.json', JSON.stringify(oldData, null, 2));
            process.exit(0);
          } else {
            console.log("No updates to proxy-map.json");
            process.exit(1); // Cancel commit step
          }
          EOF

      - name: Commit and push if changed
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add proxy-map.json
          git commit -m "🔄 Update proxy-map.json from Glitch data"
          git push
